### ISSUE TITLE
TypeError: Cannot read property 'saveDateOnly' of undefined

### ISSUE THREAD

**Issue by saiteja77** [boblauer/dateonly#5]
I got this issue when I tried to define my schema with the type DateOnly

const mongoose = require('mongoose');
var DateOnly = require('dateonly')(mongoose);
const Schema = mongoose.Schema;

const ItemSchema = new Schema({
    name:{
        type: String,
        required: true
    },
    date:{
        **type: DateOnly,** 
        default: Date.now
    }
});

And then when I tried to run my project I keep on getting the following error

C:\Users\Acer\Desktop\Projects\MernStack\node_modules\dateonly\dateonly.js:17
    this.saveDateOnly(val || new Date());
         ^
TypeError: Cannot read property 'saveDateOnly' of undefined
    at DateOnly (C:\Users\Acer\Desktop\Projects\MernStack\node_modules\dateonly\dateonly.js:17:10)
    at Object.<anonymous> (C:\Users\Acer\Desktop\Projects\MernStack\models\item.js:2:35)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Acer\Desktop\Projects\MernStack\routes\api\items.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
[nodemon] app crashed - waiting for file changes before starting...

Can Anyone take a look into this?

Thanks.

**Comment by boblauer** [comment]
Can you see if removing the default of `Date.now` gets rid of the error?  I'm not suggesting that as a fix, just curious if that's the cause.

**Comment by saiteja77** [comment]
Still getting the same error.

**Comment by boblauer** [comment]
What version of Mongoose are you using?

**Comment by saiteja77** [comment]
I think its 5.2.7

**Comment by boblauer** [comment]
Missed this at first pass:

```js
var DateOnly = require('dateonly')(mongoose);
```

should be

```js
var DateOnly = require('mongoose-dateonly')(mongoose);
```

**Comment by saiteja77** [comment]
It threw an error that it cannot fin the module mongoose-dateonly

 ```
**Error: Cannot find module 'mongoose-dateonly'** 
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
[0]     at Module.require (internal/modules/cjs/loader.js:650:17)
[0]     at require (internal/modules/cjs/helpers.js:20:18)
[0]     at Object.<anonymous> (C:\Users\Acer\Desktop\Projects\MernStack\models\item.js:3:16)
[0]     at Module._compile (internal/modules/cjs/loader.js:702:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
[0]     at Module.load (internal/modules/cjs/loader.js:612:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
[0]     at Module.require (internal/modules/cjs/loader.js:650:17)
[0]     at require (internal/modules/cjs/helpers.js:20:18)
[0]     at Object.<anonymous> (C:\Users\Acer\Desktop\Projects\MernStack\routes\api\items.js:5:14)
[0]     at Module._compile (internal/modules/cjs/loader.js:702:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
[0]     at Module.load (internal/modules/cjs/loader.js:612:32)
[0] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by boblauer** [comment]
You need to install it.  `npm install mongoose-dateonly`

**Comment by saiteja77** [comment]
Thanks it worked.
